### ISSUE TITLE
WPI Network Unavailable During Maintenance

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/dev-ops#11]
https://hub.wpi.edu/news/758/august-maintenance

> The WPI network will undergo critical maintenance tonight, Thursday August 19 beginning at 11:00 PM through 2:00 AM Friday, August 20. There will be intermittent outages of connectivity between the internet and WPI network.

**Comment by calcmogul** [comment]
What timezone?

**Comment by AustinShalit** [comment]
ET
