### ISSUE TITLE
Add Google SEO to https://wpilib.org/

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/dev-ops#5]
https://developers.google.com/search/docs/data-types/logo

**Comment by AustinShalit** [comment]
Looks like Google is picking it up now. Just need to wait for the site to be crawled again: https://search.google.com/test/rich-results?utm_campaign=devsite&utm_medium=jsonld&utm_source=logo&id=XjSVN7SJYhBDTxhJqL48PQ
